language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests tests/test-listall.py tests/test-listitems.py tests/test-rulesgenerator.py tests/test-scout2.py test/test-utils.py
# use container-base infrastructure
sudo: false
