language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - '[ "${TRAVIS_SECURE_ENV_VARS}" = "false" ] && nosetests tests/test-listall.py tests/test-listitems.py tests/test-rulesgenerator.py tests/test-utils.py || false'
  - 'nosetests tests/test-scout2.py'
# use container-base infrastructure
sudo: false
